services:
  database:
    image: postgres
    container_name: postgres_database_prisma_deliveries
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=prisma_deliveries
    volumes:
      - pgdata:/data/postgres
volumes:
  pgdata:
    driver: local